---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduling-webhook-config
  namespace: kube-system
data:
  TOLERATION_KEY_APPLICATION: dedicated
  TOLERATION_VALUE_APPLICATION: application
  TOLERATION_EFFECT_APPLICATION: NoSchedule
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: scheduling-webhook
  labels:
    app: scheduling-webhook
webhooks:
  - name: scheduling-webhook.kube-system.svc
    clientConfig:
      caBundle: CA_BUNDLE_TO_BE_REPLACED_BY_CALLING_MAKE_CERT_IN_SSL_DIR
      service:
        name: scheduling-webhook
        namespace: kube-system
        path: "/mutate/application"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        type: test-application
